ids = set([1,2,3,4,5,6,7,8,9])
print(ids)
ids.add(10)
print(ids)
leng = len(ids)
print(leng)
ids1= set(range(20))
print(ids1)
males = set ([1,3,5,7,9])
females = ids - males
leng1=len(females)
print(leng1)
print ("Males id's are :", males)
print("Females id's are :", females)
everyone = males | females
print("All id's are :",everyone)
union = everyone & set([2,3,99,100])
print(union)

words =set("ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEF")
length = len(words)
print(length)
x = set ([1,2,3])
y = set ([2,3,4])
z = x.symmetric_difference(y)
print(z)