#x= " H e l l o , W o r l d "
#print (x[2:5])
#print (x.strip())
#print (len(x))
#print (x.upper())
#print(x.replace("H e l l o","Bonjour"))
#print (x.spilt(","))
import time
print ("*******String operations*********")
time.sleep(3)
print(" Compiled by : Sumit Purandare")
time.sleep(5)
name = input("Enter your name :")
time.sleep(3)
print("Hello!!",name,"\nHow are you?")
      
print("Let me give you some funny facts about your name :")
time.sleep(3)
print("Length of your name is of" ,len(name),"Characters ")
time.sleep(3)
print ("Your name starts with" , name [0])
time.sleep(3)
print ("Your name  in Upper case :" , name.upper())
time.sleep(3)
print ("Your name in lower letter :" ,name.lower())
time.sleep(3)
print("End of the program:Thank You!" )
